version: "3.4"
services:
  cook_db:
    build: ./mysql/
    container_name: cook_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - cook_db_data:/var/log/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --host=127.0.0.1 --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --port=3306"]
    ports:
      - "3306:3306"
  cook_rails:
    build: ./api/server/
    container_name: cook_api_rails
    command: ["./run.sh"]
    env_file:
      - ./api/server/.env
    volumes:
      - ./api/server/:/code/
      - cook_public:/code/public/
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    depends_on:
      cook_db:
        condition: service_healthy
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
  cook_api_nginx:
    build: ./api/nginx/
    container_name: cook_api_nginx
    volumes:
      - cook_public:/code/public/
    ports:
      - "8080:80"
    depends_on:
      cook_rails:
        condition: service_healthy
  cook_react:
    build: ./frontend/
    container_name: cook_react
    volumes:
      - ./frontend/front/:/code/
    ports:
      - "8000:8000"
    command: ["/run.sh"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
  cook_front_nginx:
    build: ./frontend/nginx/
    container_name: cook_front_nginx
    ports:
      - "80:80"
    depends_on:
      cook_react:
        condition: service_healthy
  cook_python:
    build: ./py/
    container_name: cook_python
    volumes:
      - ./:/code/
volumes:
  cook_db_data:
  cook_public:
